version: '3'
services:
  gunicorn:
    image: filewave/msp_portal:dev-1.1.0-beta1
    environment:
      - MSP_PORTAL_KEYFILE=${MSP_PORTAL_KEYFILE}
      - MSP_PORTAL_CERTFILE=${MSP_PORTAL_CERTFILE}
      - MSP_PORTAL_DJANGO_SECRET_KEY=${MSP_PORTAL_DJANGO_SECRET_KEY:?MSP_PORTAL_DJANGO_SECRET_KEY is required}
      - MSP_PORTAL_HOSTNAME=${MSP_PORTAL_HOSTNAME:?MSP_PORTAL_HOSTNAME is required}
  rqscheduler:
    image: filewave/msp_portal:dev-1.1.0-beta1
    environment:
      - MSP_PORTAL_DJANGO_SECRET_KEY=${MSP_PORTAL_DJANGO_SECRET_KEY:?MSP_PORTAL_DJANGO_SECRET_KEY is required}
      - MSP_PORTAL_HOSTNAME=${MSP_PORTAL_HOSTNAME:?MSP_PORTAL_HOSTNAME is required}
  rqworker:
    image: filewave/msp_portal:dev-1.1.0-beta1
    environment:
      - MSP_PORTAL_DJANGO_SECRET_KEY=${MSP_PORTAL_DJANGO_SECRET_KEY:?MSP_PORTAL_DJANGO_SECRET_KEY is required}
      - MSP_PORTAL_HOSTNAME=${MSP_PORTAL_HOSTNAME:?MSP_PORTAL_HOSTNAME is required}
